-- Verification script for Regulatory Intelligence Platform

-- 1. Check schemas
SHOW SCHEMAS IN DATABASE REG_INTEL;

-- 2. Check RAW table
DESCRIBE TABLE REG_INTEL.RAW.RAW_REGULATIONS;

-- 3. Check Dynamic Tables
SHOW DYNAMIC TABLES IN DATABASE REG_INTEL;

-- 4. Verify DT scheduling state (should be ACTIVE)
SELECT name, scheduling_state, target_lag, refresh_mode 
FROM TABLE(INFORMATION_SCHEMA.DYNAMIC_TABLES())
WHERE database_name = 'REG_INTEL';

-- 5. Check Cortex Search Service
SHOW CORTEX SEARCH SERVICES IN SCHEMA REG_INTEL.ANALYTICS;

-- 6. Check Semantic View
SHOW SEMANTIC VIEWS IN SCHEMA REG_INTEL.ANALYTICS;
DESCRIBE SEMANTIC VIEW REG_INTEL.ANALYTICS.REG_ANALYTICS_VIEW;

-- 7. Check Agent
SHOW AGENTS IN SCHEMA REG_INTEL.ANALYTICS;
DESCRIBE AGENT REG_INTEL.ANALYTICS.REG_INTEL_AGENT;

-- 8. Check EAI
SHOW EXTERNAL ACCESS INTEGRATIONS LIKE 'REG_INTEL%';

-- 9. Test data flow (after Openflow ingestion)
-- SELECT COUNT(*) FROM REG_INTEL.RAW.RAW_REGULATIONS;
-- SELECT COUNT(*) FROM REG_INTEL.CURATED.DT_REG_BRONZE;
-- SELECT COUNT(*) FROM REG_INTEL.CURATED.DT_REG_SILVER;
-- SELECT COUNT(*) FROM REG_INTEL.ANALYTICS.DT_REG_GOLD;

-- 10. Test Agent (after data is loaded)
-- SELECT SNOWFLAKE.CORTEX.DATA_AGENT_RUN(
--   'REG_INTEL.ANALYTICS.REG_INTEL_AGENT',
--   'What EPA regulations were published recently?'
-- );
