-- Semantic Views for Cortex Analyst (used by the Agent)

-- 1. Company Exposure View
CREATE OR REPLACE SEMANTIC VIEW REG_INTEL.ANALYTICS.COMPANY_EXPOSURE_VIEW
  TABLES (
    EXPOSURE AS REG_INTEL.ANALYTICS.DT_COMPANY_EXPOSURE PRIMARY KEY (DOCUMENT_NUMBER, COMPANY_ID)
  )
  FACTS (
    EXPOSURE.DOCUMENT_NUMBER AS DOCUMENT_NUMBER,
    EXPOSURE.COMPANY_ID AS COMPANY_ID
  )
  DIMENSIONS (
    EXPOSURE.REGULATION_TITLE AS REGULATION_TITLE,
    EXPOSURE.REGULATORY_CATEGORY AS REGULATORY_CATEGORY,
    EXPOSURE.PUBLICATION_DATE AS PUBLICATION_DATE,
    EXPOSURE.COMPANY_NAME AS COMPANY_NAME,
    EXPOSURE.PRIMARY_TICKER AS PRIMARY_TICKER,
    EXPOSURE.PRIMARY_EXCHANGE_CODE AS PRIMARY_EXCHANGE_CODE,
    EXPOSURE.SEC_INDUSTRY_GROUP AS SEC_INDUSTRY_GROUP
  )
  METRICS (
    EXPOSURE.COMPANY_COUNT AS COUNT(DISTINCT COMPANY_ID),
    EXPOSURE.REGULATION_COUNT AS COUNT(DISTINCT DOCUMENT_NUMBER)
  );

-- 2. SEC Filings View
CREATE OR REPLACE SEMANTIC VIEW REG_INTEL.ANALYTICS.SEC_FILINGS_VIEW
  TABLES (
    FILINGS AS REG_INTEL.ANALYTICS.DT_REG_SEC_FILINGS PRIMARY KEY (DOCUMENT_NUMBER, CIK, FILED_DATE)
  )
  FACTS (
    FILINGS.DOCUMENT_NUMBER AS DOCUMENT_NUMBER,
    FILINGS.CIK AS CIK
  )
  DIMENSIONS (
    FILINGS.REGULATION_TITLE AS REGULATION_TITLE,
    FILINGS.REGULATORY_CATEGORY AS REGULATORY_CATEGORY,
    FILINGS.REGULATION_DATE AS REGULATION_DATE,
    FILINGS.FILING_COMPANY AS FILING_COMPANY,
    FILINGS.FORM_TYPE AS FORM_TYPE,
    FILINGS.FILED_DATE AS FILED_DATE,
    FILINGS.FISCAL_YEAR AS FISCAL_YEAR,
    FILINGS.PRIMARY_TICKER AS PRIMARY_TICKER
  )
  METRICS (
    FILINGS.FILING_COUNT AS COUNT(*),
    FILINGS.COMPANY_COUNT AS COUNT(DISTINCT CIK)
  );
